[tools]
python = "3.13"
pipx = "1.7.1"
"pipx:poethepoet" = "0.34.0"
"pipx:poetry" = "2.1.3"
"pipx:pre-commit" = "4.2.0"

[settings]
experimental = true

[hooks]
postinstall = [
    "pre-commit install",
    "poetry install",
]
